development:
  auth0_domain: dev-34uxk670t4va6l0u.us.auth0.com
  auth0_client_id: iEFsvBHiKL5QwdYMCHyXKjkp0Js6q255
  auth0_client_secret: -XQx8VbrfCa9qr22oFr0kBV8AP_ypqJ-COds3R0n5KJ_U7JRFFn6hvXKO5xM8yTo